### PR TITLE
Fix `as.matrix.projection()` for 1 (clustered) draw

### PR DESCRIPTION
**Pull request by fweber144**
This fixes the following issue:
```r
library(projpred)
library(rstanarm)
options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
df_gaussian <- df_gaussian[1:40, ]
mydat <- cbind("y" = df_gaussian$y, as.data.frame(df_gaussian$x))
mydat$mygroup <- gl(n = 8, k = floor(nrow(mydat) / 8),
                    labels = paste0("gr", seq_len(8)))
set.seed(457211)
mydat$noise <- rnorm(nrow(mydat))
mygroup_icpts_truth <- rnorm(nlevels(mydat$mygroup), sd = 6)
mygroup_V1_truth <- rnorm(nlevels(mydat$mygroup), sd = 6)
mydat$y <- mydat$y + mygroup_icpts_truth[as.numeric(mydat$mygroup)]
mydat$y <- mydat$y + mygroup_V1_truth[as.numeric(mydat$mygroup)] * mydat$V1

myfit <- stan_glmer(y ~ V1 + V2 + V3 + V4 + V5 + noise + (1 + V1 | mygroup),
                    data = mydat,
                    seed = 1140350788)

myproj <- project(myfit,
                  solution_terms = c("(1 | mygroup)"),
                  nclusters = 1)
myprjmat <- as.matrix(myproj)
str(myprjmat)
## Previously (on branch `develop`), this gave:
# List of 2
# $ :'data.frame':	8 obs. of  1 variable:
#   ..$ (Intercept): num [1:8] 2.25 3.3 1.23 -6.04 8.19 ...
# $ : num 9.03
# - attr(*, "dim")= int [1:2] 1 2
# - attr(*, "dimnames")=List of 2
# ..$ : NULL
# ..$ : chr [1:2] "b_mygroup" "sigma"
##
## With the fix from this PR, this gives:
# num [1, 1:11] 2.2269 5.8988 0.0264 1.0743 -0.9944 ...
# - attr(*, "dimnames")=List of 2
# ..$ : NULL
# ..$ : chr [1:11] "b_Intercept" "sd_mygroup__Intercept" "r_mygroup[gr1,Intercept]" "r_mygroup[gr2,Intercept]" ...
##

```
The reason for this issue was the hard-coded use of `as.matrix.lm()` in the `!inherits(x$sub_fit, "list")` case in `as.matrix.projection()` (see commit abdb58d). Everything else is just needed to avoid those hard-coded `as.matrix.<class_name>()` method calls in the former `inherits(x$sub_fit, "list")` case of `as.matrix.projection()`.

Note that I removed the `as.matrix.noquote()` method since it doesn't seem to be used and since it overwrites `as.matrix.noquote()` from the "base" package, causing a NOTE (or WARNING? I don't remember) by R CMD check.

### CODE REVIEW

**Comment by fweber144** [comment]
The GLMM vignette gives an error now. Please wait with the merge. I'll ping you when this PR is ready to be merged.

**Comment by fweber144** [comment]
Should be fixed now and ready to be merged. The original problem with the GLMM vignette was that I had forgotten to add a `as.matrix.glmerMod()` method redirecting to `as.matrix.lmerMod()`, so the Poisson example (where the submodels are `"glmerMod"` objects) failed.

For safety, I have now added an error message for an unavailable `as.matrix.<class_name>()` method.

I have also added a `as.matrix.gamm4()` method. As done implicitly before this PR, `as.matrix.gamm4()` redirects to `as.matrix.lm()`. However, I think this is a mistake, as I could confirm in a reprex which I'll put in a new issue on the issue tracker. Note that I didn't add a `as.matrix.gam()` method since objects of class `"gam"` seem to inherit from `"glm"` and `"lm"`, so should automatically be redirected (dispatched) to `as.matrix.glm()` which in turn redirects to `as.matrix.lm()`.

So I think all submodel classes currently used by projpred should have an appropriate `as.matrix.<class_name>()` method.

Commit 34d9403 and the `%:::%`-related commits are just for cleaning.

**Comment by fweber144** [comment]
The GAMM issue mentioned above may now be found under #131.

**Comment by fweber144** [comment]
Just updated the NEWS file.

**Comment by AlejandroCatalina** [comment]
Can we have tests for this?

**Comment by fweber144** [comment]
Yes, I'll add them.

**Comment by fweber144** [comment]
I've added the requested tests in PR #132.

**Comment by AlejandroCatalina** [comment]
Can you rebase this on top of new develop?

**Comment by fweber144** [comment]
Yep

**Comment by fweber144** [comment]
I've chosen a merge to avoid a forced push. I hope that's ok for you. I've also added commit 078b10d which fixes a previous typo in the documentation.

**Pull request merged**
