### PR TITLE
Fixes for no-intercept models

### PR DESCRIPTION
**Pull request by fweber144**
This is related to #96 and tries to fix issues occurring for reference models which do not have an intercept (so that the intercept has to be excluded from the projected submodels, too). Notes:

* I have only looked at the reprex from #96 which uses `project()`. In particular, I haven't looked at the projection(s) happening in `varsel()` and `cv_varsel()` calls for no-intercept reference models. I hope `varsel()` and `cv_varsel()` should also work now appropriately for that case, but I'm not 100% sure. Better check this.
* I haven't looked at the C++ code from `glm_ridge_c()` to see whether the intercept is properly taken into account there at all places where it needs to. But the fact that it has an argument `intercept` and that it returns an intercept of 0 for the reprex from #96 makes me hope that it should. However, you should probably check that.
* Currently, for no-intercept reference models, the object returned by `as.matrix.projection()` still contains a column for the intercept, but it's only zeros. Perhaps (for user-friendliness) it might be better to omit this zero-column.

### CODE REVIEW

**Comment by AlejandroCatalina** [comment]
This should translate directly to `varsel()` and `cv_varsel()`, but it's best to add proper tests to `test_varsel.R` and `test_project.R`. Can you do that? Namely, fit `varsel` and `cv_varsel` both with and without intercepts and check that the submodels act accordingly, then project those `vsel` objects and check that intercept works as intended.

**Comment by fweber144** [comment]
Yep, I'll do that.

**Comment by fweber144** [comment]
Ok, this whole thing is more complex than I thought. First of all, my PR broke existing code for models which *do* have an intercept (so the majority of models). I'm sorry for that; I forgot to run the unit tests from **testthat**. I just pushed some commits which should fix at least that. Now I'll still have to adopt `varsel()` and `cv_varsel()` to no-intercept models. But that might take me some time since it requires more changes than I would have thought.

**Comment by fweber144** [comment]
I think I'll be stopping here for now. As stated in the message of the last commit I just pushed, this PR probably needs more adjustments. The error messages I added in that last commit account for the unfinished state of this PR. If this PR doesn't get merged into `develop`, then I think at least the error messages should be added to `develop` (so that [this reprex](https://github.com/stan-dev/projpred/issues/96#issuecomment-808375740) throws an error).

If I get the time, I can perhaps continue working on this, but for now I'm lacking that time.

**Comment by AlejandroCatalina** [comment]
Closing for now with #124 .

**Pull request closed without merging**
