### PR TITLE
Fix issue when projecting with non-NULL `solution_terms`

### PR DESCRIPTION
**Pull request by fweber144**
This should fix issue #79.

### CODE REVIEW

**Comment by AlejandroCatalina** [comment]
I was aware of this but unfortunately hadn’t had time to fix it yet. I’ll take a look, thanks!

Best,
Alejandro

**Comment by fweber144** [comment]
Thanks for merging. I'm really sorry, but I just realized that I messed up the NEWS.md by this PR. I'll fix it and create a new PR for that fix (to be merged before #82).

**Comment by AlejandroCatalina** [comment]
It’s okay, I fixed news already.

Best,
Alejandro

**Comment by fweber144** [comment]
> It’s okay, I fixed news already. Best, Alejandro

Thanks. But I think the NEWS.md line
```
* Fixed a bug raising an error when not projecting from a `vsel` object.
```
should be moved up to section "Bug fixes" under 2.0.4.9000 as it was performed under 2.0.4.9000. Sorry for the mess.

**Comment by fweber144** [comment]
I can fix that, if you want. Then I'll also add the PR numbers to the corresponding NEWS items.

**Comment by AlejandroCatalina** [comment]
Okay!

Best,
Alejandro

**Pull request merged**
