### PR TITLE
as.matrix.lmerMod(): Extract random effects

### PR DESCRIPTION
**Pull request by fweber144**
It would be nice if `as.matrix.lmerMod()` would also extract the (estimated) random effects themselves. Or are there any theoretical arguments against that? If not, then the code from this PR could perform that extraction. Note that the essential call is that to `lme4::ranef()`; the code from commit 5fa6d3f792546ee38d72fcb67ba473369f3559c3 is just for adding meaningful names.

This is the second of the two PRs mentioned [here](https://github.com/stan-dev/projpred/issues/72#issuecomment-775073670). Because of the multiple parameters (multiple random effects) per group-level term, this PR builds upon PR #73 to ensure that `as.matrix.projection()` handles the column names of its output matrix correctly.

Furthermore, this PR builds upon PR #74 since PR #74 is enhanced by this PR: If `as.matrix.lmerMod()` returns the random effects themselves, then the user may calculate their empirical SD manually.

**EDITS:**
* [Here](https://github.com/fweber144/projpred/compare/fweber144:proj_mat_fix..fweber144:proj_mat_ranef) is the diff for this PR and PR #73.
* [Here](https://github.com/fweber144/projpred/compare/fweber144:proj_mat_varcomp..fweber144:proj_mat_ranef) is the diff for this PR and PR #74.

### CODE REVIEW

**Comment by AlejandroCatalina** [comment]
I think this makes sense. I'll pull it locally and check the behaviour. 

Thanks!

**Comment by AlejandroCatalina** [comment]
I merged it into develop now. I understand that merging this one renders the other PRs outdated?

**Comment by fweber144** [comment]
Yes, exactly. I'll close them.

**Comment by fweber144** [comment]
The only remaining question for me is what you think about https://github.com/stan-dev/projpred/pull/73#issuecomment-775288868 because line https://github.com/stan-dev/projpred/blob/dc1c3e473c8df2298e956c406499ddac941e5c5f/R/methods.R#L720 still uses `x$solution_terms`.

**Comment by AlejandroCatalina** [comment]
Yes, that's a good point. I'll use `colnames(res)` instead because of contrasts and whatnot.

**Comment by AlejandroCatalina** [comment]
Up in develop.

I'll work on fixing each group effect's name in the resulting matrix as we have now syntax like `year.Intercept.1999` and we'd ideally want something like `(Intercept | year.1999)` probably.

**Comment by fweber144** [comment]
> Up in develop.

Thanks!

> I'll work on fixing each group effect's name in the resulting matrix as we have now syntax like `year.Intercept.1999` and we'd ideally want something like `(Intercept | year.1999)` probably.

Yeah, that's a design question which you have to decide. Personally, I like the current naming. For the reprex posted [here](https://github.com/stan-dev/projpred/issues/72#issue-803367733), the current column names are
```
 [1] "Intercept"                "V1"                       "V3"                       "V5"                      
 [5] "noise"                    "V4"                       "V2"                       "mygroup.sd.Intercept"    
 [9] "mygroup.sd.V1"            "mygroup.cor.Intercept.V1" "mygroup.Intercept.gr1"    "mygroup.Intercept.gr2"   
[13] "mygroup.Intercept.gr3"    "mygroup.Intercept.gr4"    "mygroup.Intercept.gr5"    "mygroup.Intercept.gr6"   
[17] "mygroup.Intercept.gr7"    "mygroup.Intercept.gr8"    "mygroup.V1.gr1"           "mygroup.V1.gr2"          
[21] "mygroup.V1.gr3"           "mygroup.V1.gr4"           "mygroup.V1.gr5"           "mygroup.V1.gr6"          
[25] "mygroup.V1.gr7"           "mygroup.V1.gr8"           "sigma" 
```
which shows some kind of hierarchical structure, from most general (`mygroup`) to most specific (`gr1`, `gr2`, and so on), with the parameters (`sd` and `cor` or nothing for the random effects themselves) and the coefficient they refer to (`Intercept` and `V1`) in between.

The `(Intercept | year.1999)` syntax has the downside that `(Intercept | year.1999)` could also be the group-level intercept of a group called `year.1999`. But of course, no naming scheme is perfect and the current scheme also has its downsides. For example, it relies heavily on dots, which might be less desirable if the user uses dots in the variable names, too.

**Comment by fweber144** [comment]
An idea might also be to use brms' naming scheme. For the reprex I just mentioned, this would give
```
 [1] "b_Intercept"                "b_V1"                       "b_V3"                       "b_V5"                      
 [5] "b_noise"                    "b_V4"                       "b_V2"                       "sd_mygroup__Intercept"     
 [9] "sd_mygroup__V1"             "cor_mygroup__Intercept__V1" "r_mygroup[gr1,Intercept]"   "r_mygroup[gr2,Intercept]"  
[13] "r_mygroup[gr3,Intercept]"   "r_mygroup[gr4,Intercept]"   "r_mygroup[gr5,Intercept]"   "r_mygroup[gr6,Intercept]"  
[17] "r_mygroup[gr7,Intercept]"   "r_mygroup[gr8,Intercept]"   "r_mygroup[gr1,V1]"          "r_mygroup[gr2,V1]"         
[21] "r_mygroup[gr3,V1]"          "r_mygroup[gr4,V1]"          "r_mygroup[gr5,V1]"          "r_mygroup[gr6,V1]"         
[25] "r_mygroup[gr7,V1]"          "r_mygroup[gr8,V1]"          "sigma"
```

**Comment by AlejandroCatalina** [comment]
That might work as well, and would be good for consistency in the ecosystem.

Best,
Alejandro

**Pull request merged**
