### PR TITLE
Support models fit with brms

### PR DESCRIPTION
**Pull request by paul-buerkner**
With this PR, models fit with brms should be supported by projpred. 
I validated the implementation against that of rstanarm.

@jpiironen Can you review and test this PR?
You will need to install brms from the GitHub branch "support-projpred" for full functionality.

### CODE REVIEW

**Comment by jpiironen** [comment]
Thanks Paul!  And sorry for being unreachable for a few days. I will check this as soon as possible. I suppose you ended up implementing the things you mentioned on discussion to issue #12 afterall?

**Comment by paul-buerkner** [comment]
Thanks! Yeah, I just build in workarounds for these issues.

**Comment by jpiironen** [comment]
I started checking this but ran into an error ```Error: object of type 'closure' is not subsettable``` on line 151 ```z <- model.frame(data)```. It looks like variable ```data``` is not defined before this line.

Another thing I noticed from the code: it raises an error when family is something else than gaussian, binomial or poisson, but since bernoulli (family specific to ```brms``` only) is a special case of binomial, I think that could (and should) be supported as well. But I'm not sure what would be the best way of doing this. Do you have thoughts on this?

I can do more careful checking and testing if you can fix the first error so that I can run some examples.

**Comment by paul-buerkner** [comment]
Thanks. The `data` typo is somewhat embarrassing, sorry for that. I am fixing this and enabling bernoulli asap.

**Comment by jpiironen** [comment]
Thanks, looks fine to me so far! I couldn't spot anything that would work unexpectedly.

**Comment by paul-buerkner** [comment]
Great! Thanks for reviewing my PR!

**Comment by bgoodri** [comment]
Can **projpred** 1.1 be released ASAP (like now)? The **rstanarm** tests are failing with **projpred** 1.0 on CRAN due to the way `get_refmodel.stanreg` was calling `get_y` in binomial models specified as a matrix of successes and failures. This apparently got fixed (maybe accidentally) because the tests in the master branch of **projpred** are passing. But `R CMD check` of **projpred** shows some other minor problems with documentation and so forth.

**Comment by paul-buerkner** [comment]
I have just fixed some R CMD check notes, but I don't know where the **mesquite** data set is coming from so I can't fix that.

**Comment by bgoodri** [comment]
It is under the data folder. It comes from BDA3.

**Comment by jpiironen** [comment]
Thanks for letting me know! I'll check this and update to CRAN asap.

**Comment by jpiironen** [comment]
Thanks for letting me know! I will update to CRAN asap.

**Comment by jpiironen** [comment]
I was uploading projpred to CRAN but got this note:
```
* checking dependencies in R code ... NOTE
Missing or unexported objects:
  'brms::data_response' 'brms::update_adterms'
```
@paul-buerkner are these something that you added recently and thus something not included in the current release of brms? So I was wondering should I wait for you to update brms first before updating projpred?

**Comment by paul-buerkner** [comment]
Damn yes. Let me submit a new version of brms to CRAN tonight.

Am Mo., 22. Okt. 2018 um 16:57 Uhr schrieb Juho Piironen <
notifications@github.com>:

**Comment by paul-buerkner** [comment]
brms 2.6.0 is on its way to CRAN. You should be able to release projpred now.

**Comment by jpiironen** [comment]
Submitted, and it's also on its way to CRAN now.

**Pull request merged**
