### PR TITLE
Update tests and kfold

### PR DESCRIPTION
**Pull request by AlejandroCatalina**
This PR was mainly focused on `test_datafit.R` and whatever it implied, which is a long list:

- data fit objects when the reference model does not include a proper fit
- k fold cross validation
- L1 search
- projections and predictions

This is still a work in progress, I'm checking the last point now for non gaussian families (for gaussian families it works properly). I'm double checking the linear predictions of mu and the transformation to eta.

### CODE REVIEW

**Comment by bgoodri** [comment]
I have to teach projpred Tuesday. Do you all want me to use this branch or develop or the CRAN version?

**Comment by AlejandroCatalina** [comment]
My take on his: For teaching I would go with the stable version. The overall working stays the same, so there is not much lost from not using this branch (except multilevel models). Thanks for asking tho!

**Comment by AlejandroCatalina** [comment]
Alright! All tests are passing (I checked locally, travis is still running at the time of writing). I commented some minor tests that I'll look into in a next PR (this one got too big anyway). I had to wrap the tests with `travis_wait` on the Travis build script tho. I guess the wait is due to using `brms`, that takes longer in compiling the models. In a later stage I'll try  to reduce the number of models fitted during the tests because maybe a lot of the models could be shared or something.

I will now open a new PR where I take care of smaller polishing and refactoring. After that one there will be possibly one more where we focus on removing redundancies on the code and structures returned.

**Comment by paul-buerkner** [comment]
Thanks! I think brms should not be run in tests though to avoid compilation
at run time altogether. At least not in tests designed to be run on CRAN.
Is the PR ready to be reviewed? If yes I will do it later on today.

Alejandro Catalina <notifications@github.com> schrieb am Do., 5. März 2020,
08:59:

**Comment by AlejandroCatalina** [comment]
Yes I agree. It's just that I haven't looked too much into `get_refmodel.stanreg`, which is something on the TODO list as well. 

I'm not sure how useful it is to review this PR as most of it is making sure that the tests pass (and they do now). Also, given that we are going to do another PR specifically tailored at polishing and cleaning, most of the comments about that here should be carried to that one, in my opinion.

In any case, it is ready for anyone to take a look (I will rebase it into one commit before merging to master because the commit history is full of useless commits). 

To make any reviewing faster, these are the main things involved:

- data fit objects and k fold cross validation,
- glm_elnet and glm_ridge,
- robust l1 search,
- projections and predictions tests,
- varsel and cv_varsel tests.

 So, what I think makes more sense now is to move onto the following small PRs and focus all the comments on the refactoring and polishing PR that would come last (as we discussed last week). Does this make sense to you as well?

**Comment by paul-buerkner** [comment]
So you mean we can simply merge this PR and then take a closer look at the
upcoming ones? I will only have access to my laptop later so perhaps
@avehtari could merge it earlier in this case.

Alejandro Catalina <notifications@github.com> schrieb am Do., 5. März 2020,
09:18:

**Comment by AlejandroCatalina** [comment]
Yes, I mean that. I do have access now (@avehtari made me collaborator), but I didn't want to take on any actions without talking to you before. If this is okay with you, I will go ahead and merge it so we can keep working on small stuff without delaying the process for too long.

**Comment by paul-buerkner** [comment]
Please go ahead and merge it.

Alejandro Catalina <notifications@github.com> schrieb am Do., 5. März 2020,
09:49:

**Pull request merged**
