### PR TITLE
Improve non-Gaussian projections

### PR DESCRIPTION
**Pull request by AlejandroCatalina**
Right now we solve pure ML estimates for all approximations, even for
non-Gaussian ones, what may end up in unstable or degenerate estimates for some
models. By using ridge regression we can control for this, but we need to add
MASS dependency to use lm.ridge (we want to use this to have a similar
interface to lme4).

### CODE REVIEW

**Comment by paul-buerkner** [comment]
Having the MASS dependency is fine since MASS is in the R system library anyway and thus natively shipped with R.

**Comment by AlejandroCatalina** [comment]
Running `devtools::test()` locally passes all the tests. Anybody has a clue on why it seems to fail here?

**Comment by paul-buerkner** [comment]
what happens if you run `devtools::check()`?

**Comment by AlejandroCatalina** [comment]
There are 2 failures. I'll check them. The weird thing is that they don't come up if I run `devtools::test()`. And in anywise the output is still different from Travis.

**Comment by AlejandroCatalina** [comment]
The problem I'm having is that I can't replicate the failures 😅 .

**Comment by paul-buerkner** [comment]
I will check the non-gaussian branche if I get any failues and try to fix them.

**Comment by AlejandroCatalina** [comment]
Let me know if you find a way to reproduce the failures. When I run the code that is supposed to fail it just works.

**Comment by AlejandroCatalina** [comment]
I commented out the failing tests for the moment. The bug is weird because the failing code appears in other places and it doesn't fail there. Nonetheless, I think we can keep going for the moment. If you agree, @paul-buerkner , I'll merge this and open new PRs for subsequent work.

**Comment by paul-buerkner** [comment]
Sounds good to me. Thanks!

Alejandro Catalina <notifications@github.com> schrieb am Mo., 6. Apr. 2020,
16:27:

**Pull request merged**
