### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by fweber144**
Following the fixes of issues #158 and #159, this PR adopts the tests accordingly. All tests should be passing now.

**EDIT:** I also had to adopt `test_varsel.R` to the fix for issue #167.

### CODE REVIEW

**Comment by fweber144** [comment]
Btw, I think the reason for Travis CI not running automatically is the switch from travis-ci.org to travis-ci.com, as explained in the notification shown on [projpred's travis-ci.org site](https://travis-ci.org/github/stan-dev/projpred):

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

**Comment by fweber144** [comment]
Just pushed another commit adopting `test_varsel.R` to the fix for issue #167.

**Comment by AlejandroCatalina** [comment]
Is this ready?

**Comment by fweber144** [comment]
Yes. I just ran the tests locally again (after the merged PR #174) and they succeeded. Have you already had the time to check my comment concerning Travis above?

**Comment by AlejandroCatalina** [comment]
Yes, I saw the travis warning too. I'll talk to Paul and Aki about it, as this repo belongs to Stan-dev.

**Pull request merged**
