### PR TITLE
Fixes for argument `nterms` of `proj_helper()`

### PR DESCRIPTION
**Pull request by fweber144**
See the commit messages for details.

### CODE REVIEW

**Comment by AlejandroCatalina** [comment]
This one is failing some tests for some reason. Can you take a look at that?

**Comment by fweber144** [comment]
Sure

**Comment by fweber144** [comment]
I will have to revise this.

**Comment by fweber144** [comment]
Now it should be ok. Sorry it took me a while to fix this.

**Comment by fweber144** [comment]
Just FYI: The original idea of argument `nterms` seems to have been to "filter" `object` if it already results from `project()`. That wasn't possible, though (since `list(...)$nterms` was always `NULL`). This PR does *not* try to add a new argument for this "filtering" task. This is done in PR #92.

**Comment by AlejandroCatalina** [comment]
Yeah, it happened that before the refactoring projections were handled differently. We introduced now the solution_terms argument in project that simplifies things, but earlier you could only pass integers and sometimes you wanted to predict for projections that were not done.

Best,
Alejandro

**Pull request merged**
